"""describe change

Revision ID: 1cf30acf46ce
Revises: 
Create Date: 2025-12-25 18:02:02.972128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cf30acf46ce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('userName', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('userName'),
    schema='public'
    )
    op.create_index(op.f('ix_public_groups_id'), 'groups', ['id'], unique=False, schema='public')
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('subdomain', sa.String(length=50), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['public.groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subdomain'),
    schema='public'
    )
    op.create_index(op.f('ix_public_schools_id'), 'schools', ['id'], unique=False, schema='public')
    op.create_table('school_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=True),
    sa.Column('session_year', sa.Integer(), nullable=False),
    sa.Column('schema_name', sa.String(length=63), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['public.schools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schema_name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_school_sessions_id'), 'school_sessions', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_school_sessions_id'), table_name='school_sessions', schema='public')
    op.drop_table('school_sessions', schema='public')
    op.drop_index(op.f('ix_public_schools_id'), table_name='schools', schema='public')
    op.drop_table('schools', schema='public')
    op.drop_index(op.f('ix_public_groups_id'), table_name='groups', schema='public')
    op.drop_table('groups', schema='public')
    # ### end Alembic commands ###
