"""describe change

Revision ID: 24be75122149
Revises: 1cf30acf46ce
Create Date: 2025-12-25 19:08:02.000172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24be75122149'
down_revision: Union[str, Sequence[str], None] = '1cf30acf46ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('school_sessions_school_id_fkey'), 'school_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'school_sessions', 'schools', ['school_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('schools', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('schools_group_id_fkey'), 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'groups', ['group_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('schools_group_id_fkey'), 'schools', 'groups', ['group_id'], ['id'])
    op.drop_column('schools', 'is_active')
    op.drop_constraint(None, 'school_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('school_sessions_school_id_fkey'), 'school_sessions', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###
