"""describe change

Revision ID: 9bafe353a680
Revises: 80dfd9779e22
Create Date: 2025-12-26 16:58:25.949408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bafe353a680'
down_revision: Union[str, Sequence[str], None] = '80dfd9779e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('mobile', sa.String(length=20), nullable=False))
    op.drop_constraint(op.f('groups_userName_key'), 'groups', type_='unique')
    op.create_unique_constraint(None, 'groups', ['mobile'], schema='public')
    op.drop_column('groups', 'userName')
    op.drop_constraint(op.f('school_sessions_school_id_fkey'), 'school_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'school_sessions', 'schools', ['school_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('schools_group_id_fkey'), 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'groups', ['group_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('schools_group_id_fkey'), 'schools', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'school_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('school_sessions_school_id_fkey'), 'school_sessions', 'schools', ['school_id'], ['id'])
    op.add_column('groups', sa.Column('userName', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'groups', schema='public', type_='unique')
    op.create_unique_constraint(op.f('groups_userName_key'), 'groups', ['userName'], postgresql_nulls_not_distinct=False)
    op.drop_column('groups', 'mobile')
    # ### end Alembic commands ###
