"""describe change

Revision ID: ad258843d2b6
Revises: e25b1d148507
Create Date: 2025-12-26 18:21:00.292714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad258843d2b6'
down_revision: Union[str, Sequence[str], None] = 'e25b1d148507'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('school_sessions_school_id_fkey'), 'school_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'school_sessions', 'schools', ['school_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('schools', sa.Column('custom_domain', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('address', sa.String(length=255), nullable=False))
    op.add_column('schools', sa.Column('phone', sa.String(length=15), nullable=False))
    op.add_column('schools', sa.Column('email', sa.String(length=100), nullable=False))
    op.add_column('schools', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('schools', sa.Column('user_name', sa.String(length=100), nullable=False))
    op.add_column('schools', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'schools', ['custom_domain'], schema='public')
    op.drop_constraint(op.f('schools_group_id_fkey'), 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'groups', ['group_id'], ['id'], source_schema='public', referent_schema='public')
    op.add_column('students', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('middle_name', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('students', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    op.drop_column('students', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('students', 'date_of_birth')
    op.drop_column('students', 'last_name')
    op.drop_column('students', 'middle_name')
    op.drop_column('students', 'first_name')
    op.drop_constraint(None, 'schools', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('schools_group_id_fkey'), 'schools', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'schools', schema='public', type_='unique')
    op.drop_column('schools', 'password')
    op.drop_column('schools', 'user_name')
    op.drop_column('schools', 'status')
    op.drop_column('schools', 'email')
    op.drop_column('schools', 'phone')
    op.drop_column('schools', 'address')
    op.drop_column('schools', 'custom_domain')
    op.drop_constraint(None, 'school_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('school_sessions_school_id_fkey'), 'school_sessions', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###
