"""describe change

Revision ID: efb02b6f55ca
Revises: 46f71d49ed31
Create Date: 2025-12-27 15:38:40.786934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efb02b6f55ca'
down_revision: Union[str, Sequence[str], None] = '46f71d49ed31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('school_sessions_school_id_fkey'), 'school_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'school_sessions', 'schools', ['school_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_unique_constraint(None, 'schools', ['phone'], schema='public')
    op.drop_constraint(op.f('schools_group_id_fkey'), 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'groups', ['group_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('schools_group_id_fkey'), 'schools', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'schools', schema='public', type_='unique')
    op.drop_constraint(None, 'school_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('school_sessions_school_id_fkey'), 'school_sessions', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###
