"""describe change

Revision ID: fac3d9295504
Revises: ad258843d2b6
Create Date: 2025-12-26 18:39:58.288498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac3d9295504'
down_revision: Union[str, Sequence[str], None] = 'ad258843d2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('school_sessions_school_id_fkey'), 'school_sessions', type_='foreignkey')
    op.create_foreign_key(None, 'school_sessions', 'schools', ['school_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint(op.f('schools_group_id_fkey'), 'schools', type_='foreignkey')
    op.create_foreign_key(None, 'schools', 'groups', ['group_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'schools', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('schools_group_id_fkey'), 'schools', 'groups', ['group_id'], ['id'])
    op.drop_constraint(None, 'school_sessions', schema='public', type_='foreignkey')
    op.create_foreign_key(op.f('school_sessions_school_id_fkey'), 'school_sessions', 'schools', ['school_id'], ['id'])
    # ### end Alembic commands ###
